### ISSUE TITLE
[map] Operacja degree

### ISSUE THREAD

**Issue by PawelBogdan** [PawelBogdan/JavaPolynomials#12]
Podobnie jak operacja degree dla expression, ale w związku z tym, że to jest prostsze zadanie, proszę o przypisywanie się maksymalnie dwuosobowej grupy.

**Comment by Dannmenn** [comment]
Metody do wyliczania najwyższego stopnia są już gotowe. Pytanie tylko czy dane wejściowe na tym etapie też powinny być parsowane z różnych zapisów? Na ten moment metody działają tylko w przypadku podania zmiennych pasujących do wyrażenia regularnego "x_[1-9][0-9]*".

**Comment by PawelBogdan** [comment]
Czy możemy o tym porozmawiać na zajęciach?
