### ISSUE TITLE
[map] Substitute

### ISSUE THREAD

**Issue by PawelBogdan** [PawelBogdan/JavaPolynomials#14]
Napisanie możliwości, która pozwoli zamienić liść w drzewie na dowolne wyrażenie. 
Przykład:
Wyrażenie:
x_1*x_2 + x_1^2 + x_2*x_3
chcę zrobić podstawienie: x_1 -> x_2*x_3
więc w wyniku chcę dostać:
(x_2*x_3)*x_2 + (x_2*x_3)^2 + x_2*x_3 = x_2^2*x_3 + x_2^2*x_3^3 + x_2*x_3

Część druga tego tasku będzie umożliwiała zastępować bardziej złożone wyrażenia np: x_1^3 -> wyrażenie

**Comment by Dannmenn** [comment]
Metoda do zamiany dowolnego wyrażenia na inne jest gotowa. Na ten moment przyjmuje jako wyrażenia stałą i zmienne w określonym formacie, ale może zostać użyty dowolny separator z wyjątkiem +, który jest sprawdzany. Pytanie jak bardzo ta metoda ma być odporna na wprowadzane wyrażenia?

**Comment by PawelBogdan** [comment]
Obawiam się, że nie rozumiem pytania:(
