### ISSUE TITLE
Implement parsing polynomial from string to map

### ISSUE THREAD

**Issue by PawelBogdan** [PawelBogdan/JavaPolynomials#8]

**Comment by PawelBogdan** [comment]
Trzeba dodać możliwość, żeby możliwe było sparsowanie wyrażnia:
x_1 + (x_1 + x_2)^3

**Comment by lukamate** [comment]
Przygotowałem już sobie większość kodu i wyrażeń regularnych do obsługi bardziej złożonych wielomianów. Przed weekendem powinienem to skończyć, razem z testami.
