### ISSUE TITLE
[expression] Operacja degree

### ISSUE THREAD

**Issue by PawelBogdan** [PawelBogdan/JavaPolynomials#9]
Zadanie polega na zaimplementowaniu dwóch funkcji, które będą liczyły najwyższy stopień w jakim występuje zmienna w wyrażeniu oraz najwyższy stopień, w jakim występuje lista zmiennych w wyrażeniu.

Przykłady:
ex = "x_1*x_2+ x_1*x_3 + x_1^3 + x_1*x_2*x_3"
degree(x_1) = 3
degree([x_1,x_2,x_3]) = 3

**Comment by kamillis** [comment]
ex = "x_1x_2 + x_1x_3 + (x_1^4) + x_1x_2x_3"
degree(x_1) = 4
degree([x_1,x_2,x_3]) = 4


ex = "x_1(x_2^7) + x_1x_3 + (x_1^5) + x_1(x_2^2)x_3^3"
degree(x_1) = 5
degree([x_1,x_2]) = 8
degree([x_1,x_3]) = 5
degree([x_1,x_2,x_3]) = 8

Czy jest to poprawna interpretacja implementacji metody degree()?

**Comment by PawelBogdan** [comment]
Dla pierwszego wyrażenia się zgadza:)

Dla drugiego też się zgadza:)

P.S. Z dokładnością do tego, że przy parsowaniu wyrażeń trzeba wstawiać znak mnożenia

**Comment by kpodkalicki** [comment]
Jaki jest przewidywany deadline?

**Comment by PawelBogdan** [comment]
Najlepiej by było, jakby kilka tasków dało się zamknąć we wtorek i zrobić z tego kolejny release.
